refactor: ci.yml
- 들여쓰기 수정

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,10 +39,10 @@ jobs:
         run: |
             echo "Checking coverage threshold..."
             if [ -f "build/reports/jacoco/test/jacocoTestReport.xml" ]; then
-            echo "Coverage report found"
+              echo "Coverage report found"
             else
-            echo "Coverage report not found"
-            exit 1
+              echo "Coverage report not found"
+              exit 1
             fi
 
       # JaCoCo 커버리지 리포트를 아티팩트로 업로드
@@ -56,7 +56,7 @@ jobs:
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v4
         with:
-          files: ./build/reports/jacoco/test/jacocoTestReport.xml
+          file: ./build/reports/jacoco/test/jacocoTestReport.xml
           flags: unittests
           name: codecov-umbrella
           fail_ci_if_error: false
